name: Release

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/assemble_trustroot_repository-linux-amd64 ./cmd
          GOOS=linux GOARCH=arm64 go build -o dist/assemble_trustroot_repository-linux-arm64 ./cmd
          GOOS=darwin GOARCH=amd64 go build -o dist/assemble_trustroot_repository-darwin-amd64 ./cmd
          GOOS=darwin GOARCH=arm64 go build -o dist/assemble_trustroot_repository-darwin-arm64 ./cmd

      - name: Bump version and create release
        id: bump_version
        uses: conventional-changelog/standard-version@v9
        with:
          release-as: auto

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/assemble_trustroot_repository-linux-amd64
            dist/assemble_trustroot_repository-linux-arm64
            dist/assemble_trustroot_repository-darwin-amd64
            dist/assemble_trustroot_repository-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
